CHANGELOG.md
install_functions/manager.sh

Closes: https://github.com/wazuh/wazuh-installation-assistant/issues/28
The aim of this PR is to fix the Wazuh API validation incoporated in https://github.com/wazuh/wazuh-packages/pull/3059.
> [!TIP]
> Instead comparing the Wazuh API output with the exact string `error: 0`, the fix consist in using the substring operator. This means that the Wazuh API validation will be passed if the Wazuh API output **contains** the string `error: 0`.
The fix has been debugged in order to check the correct behavior:
```console
20/08/2024 11:07:42 INFO: Checking Wazuh API connection
+ [[ {
"data": {
"affected_items": [],
"total_affected_items": 0,
"total_failed_items": 0,
"failed_items": []
},
"message": "no agent information was returned",
"error": 0
} =~ "error": 0 ]]
+ common_logger 'Wazuh API …
```

Fixed Wazuh API validation

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
.github/workflows/Test_installation_assistant_tier.yml

Related: https://github.com/wazuh/wazuh-installation-assistant/issues/20
The aim of this PR is to add the header of the new workflows `Test_installation_assistant.yml`, `Test_installation_assistant_tier.yml` and `Test_installation_assistant_distributed.yml`. These workflows represent the old `Test_unattended` Jenkins pipelines.
It is necessary to add this header to the `main` branch in order to test the workflow and finish its development.

Added Test installation assistant workflows

---

.github/actions/offline-installation/common.sh
.github/actions/offline-installation/offline-installation.sh
.github/actions/passwords-tool/tests-stack-failure.sh
.github/actions/passwords-tool/tests-stack-success.sh
.github/workflows/offline-installation.yml
.github/workflows/password-tool.yml

Related: https://github.com/wazuh/wazuh-installation-assistant/issues/19
The aim of this PR is to migrate the existing Installation assistant workflows to the new repository. These workflows were developed in the [wazuh-packages](https://github.com/wazuh/wazuh-packages.git) repository. Specifically:
- The offline installation workflow: to test the offline installation (not using the -of option, as this workflow was developed before the -of option)
- Password tool test workflow: Test the password tool behavior and ensure that the passwords are correctly changed.

Migrated existing Installation assistant workflows

---

.gitignore

Related: https://github.com/wazuh/wazuh-installation-assistant/issues/41
The aim of this PR is to add the `.gitignore` file to the repository in order to not track some files when developing.

Added gitignore file to the repository

---

CHANGELOG.md
install_functions/manager.sh

Related: https://github.com/wazuh/wazuh-installation-assistant/issues/44
The aim of this PR is to add a validation to the `TOKEN` variable when checking the Wazuh manager status.
Before this fix, the Wazuh manager API may not be ready, and then the `TOKEN` variable is empty. With this fix, a retry block has been added to fetch the token. If the token can not be fetched, the installation is roll-backed.
<details><summary>Wazuh manager installation</summary>
```console
[root@ip-172-31-84-123 cloud-user]# bash wazuh-install.sh -ws wazuh-server -v
30/08/2024 10:53:35 DEBUG: Checking root permissions.
30/08/2024 10:53:35 DEBUG: Checking sudo package.
30/08/2024 10:53:35 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
30/08/2024 10:53:35 INFO: Verbose logging redirected to …
```

Fixed token variable empty in Wazuh manager check

---

CHANGELOG.md
install_functions/manager.sh

Closes: https://github.com/wazuh/wazuh-installation-assistant/issues/51
The aim of this PR is to fix the Wazuh manager service check distributed deployments. The fix consists in changing the credentials when getting the API token in the Wazuh manager worker nodes. These nodes are installed after the master node, and the master node changes the API passwords, so the worker node must use the changed password.
Apart from the fix, a new validation has been added to the loop to check that the API token is not empty. The new validation controls if the API generates a cluster error, which is produced when the master and worker nodes are installed simultaneously. This scenario is not contemplated in the documentation, as the manager nodes are installed sequentially. However, with this …

Fixed manager check in distributed deployment

---

.github/workflows/builder_installation_assistant.yml

The aim of this PR is to include the `builder_installation_assistant.yml` GHA workflow header in the `main` branch to continue working on it.
- #55

Add build installation assistant header

---

.github/workflows/builder_installation_assistant.yml
CHANGELOG.md

The purpose of this PR is to migrate the Jenkins pipeline responsible for building the various files of the installation assistant to GitHub Actions.
The built files are copied to a specific S3 bucket in AWS.
- Files generated without the `is stage` option will be built using the commit SHA that triggered the workflow (e.g., `wazuh-install-71882dd.sh`). 
- Files created with the `is_stage` option will be generated without the commit SHA (e.g., `wazuh-install.sh`).
All the tests performed, including both the workflow execution and testing of the various files, can be seen below:
- https://github.com/wazuh/wazuh-installation-assistant/issues/55#issuecomment-2364046218
- https://github.com/wazuh/wazuh-installation-assistant/issues/55#issuecomment-2371728894
- #55

Create GHA workflow to build Wazuh Installation Assistant files

---

CHANGELOG.md
passwords_tool/passwordsFunctions.sh

related: https://github.com/wazuh/wazuh/issues/22751
```console
root@ubuntu-jammy:~# bash wazuh-passwords-tool.sh -a -A -au wazuh-wui -ap 8faZTnNdWa12ZlImls7r?iN8IFIK8Wn0
27/09/2024 14:44:33 INFO: Updating the internal users.
27/09/2024 14:44:35 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
27/09/2024 14:44:41 INFO: The filebeat.yml file has been updated to use the Filebeat Keystore username and password.
27/09/2024 14:45:04 INFO: The password for user admin is cjMnxB.BU6F1Mpd3Ly6qDW?x9JqgiZ7V
27/09/2024 14:45:04 INFO: The password for user anomalyadmin is pW*GfV9nyFN3w35Md8mjr8RL2X3ltzTM
27/09/2024 14:45:04 INFO: The password for user kibanaserver is …
```

Fixed API password change to match the user in wazuh.yml

---

CHANGELOG.md
install_functions/installCommon.sh
passwords_tool/passwordsFunctions.sh

related: https://github.com/wazuh/wazuh-packages/pull/2953
```console
root@cbordon-8722:~# bash wazuh-install.sh -a
27/09/2024 15:31:56 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
27/09/2024 15:31:56 INFO: Verbose logging redirected to /var/log/wazuh-install.log
27/09/2024 15:32:14 INFO: Verifying that your system meets the recommended minimum hardware requirements.
27/09/2024 15:32:14 INFO: Wazuh web interface port will be 443.
27/09/2024 15:32:19 INFO: --- Dependencies ----
27/09/2024 15:32:19 INFO: Installing apt-transport-https.
27/09/2024 15:32:23 INFO: Installing debhelper.
27/09/2024 15:32:51 INFO: Wazuh repository added.
27/09/2024 15:32:51 INFO: --- Configuration files ---
27/09/2024 …
```

Improved service status and output management in Installation assistant

---

CHANGELOG.md
install_functions/installMain.sh
install_functions/installVariables.sh

related: https://github.com/wazuh/wazuh-packages/pull/2962/files
```console
root@ubuntu-jammy:~# bash wazuh-install.sh -a
30/09/2024 13:16:30 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
30/09/2024 13:16:30 INFO: Verbose logging redirected to /var/log/wazuh-install.log
30/09/2024 13:16:35 INFO: Verifying that your system meets the recommended minimum hardware requirements.
30/09/2024 13:16:35 INFO: Wazuh web interface port will be 443.
30/09/2024 13:16:43 INFO: Wazuh repository added.
30/09/2024 13:16:43 INFO: --- Configuration files ---
30/09/2024 13:16:43 INFO: Generating configuration files.
30/09/2024 13:16:43 INFO: Generating the root certificate.
30/09/2024 13:16:43 INFO: Generating Admin …
```

Fixed typo in Wazuh Installation Assistant.

---

CHANGELOG.md
passwords_tool/passwordsFunctions.sh
passwords_tool/passwordsMain.sh

related: https://github.com/wazuh/wazuh-packages/pull/2968
```console
root@ubuntu-jammy:~# bash wazuh-passwords-tool.sh -gf wazuh-passwords_update.txt.
root@ubuntu-jammy:~# cat wazuh-passwords_update.txt. 
indexer_username: 'admin'
indexer_password: '6bmHa3u7Pa5F50c1G2MI*MG+efnpLLQn'
indexer_username: 'anomalyadmin'
indexer_password: 'uGFBKFriTfo1Y5h24Sj9GRq?LgE5seG5'
indexer_username: 'kibanaserver'
indexer_password: 'celNOV1OuepZXdsR*2ePm6xHFaSsnUkD'
indexer_username: 'kibanaro'
indexer_password: '6tf+S8.S4Xn0L91aU.59Nqy27K54XCTt'
indexer_username: 'logstash'
indexer_password: 'eThLjeuchqqbG9w?CKUv.oLXPmGXxw90'
indexer_username: 'readall'
indexer_password: '0os81flsm0syuijbsXZZRAFSbz+LVmJk'
indexer_username: …
```

Solve bugs when changing passwords in the manager, indexer and dashboard services.

---

CHANGELOG.md
cert_tool/certFunctions.sh
cert_tool/certMain.sh

related: https://github.com/wazuh/wazuh-packages/pull/2998
```console
root@ubuntu-jammy:~# bash wazuh-install.sh -a
30/09/2024 14:34:23 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
30/09/2024 14:34:23 INFO: Verbose logging redirected to /var/log/wazuh-install.log
30/09/2024 14:34:30 INFO: Verifying that your system meets the recommended minimum hardware requirements.
30/09/2024 14:34:30 INFO: Wazuh web interface port will be 443.
30/09/2024 14:34:37 INFO: Wazuh repository added.
30/09/2024 14:34:37 INFO: --- Configuration files ---
30/09/2024 14:34:37 INFO: Generating configuration files.
30/09/2024 14:34:38 INFO: Generating the root certificate.
30/09/2024 14:34:38 INFO: Generating Admin …
```

Change cert-tool to use only one wazuh-certificates folder.

---

CHANGELOG.md
cert_tool/certFunctions.sh

related: https://github.com/wazuh/wazuh-packages/pull/3006
releated: https://github.com/wazuh/wazuh-installation-assistant/issues/78
```console
root@ubuntu-jammy:~# cat config.yml 
nodes:
indexer:
- name: wazuh-indexer
ip: www.google.es
server:
- name: wazuh-server
ip: www.google.es
dashboard:
- name: wazuh-dashboard
ip: www.google.es
```
```console
root@ubuntu-jammy:~# bash wazuh-certs-tool.sh -A -v
30/09/2024 14:53:59 INFO: Verbose logging redirected to /root/wazuh-certificates-tool.log
30/09/2024 14:53:59 DEBUG: Reading configuration file.
30/09/2024 14:53:59 ERROR: The DNS www.google.es is not valid.
```

Added check when generating certificates for multiple DNS.

---

CHANGELOG.md
common_functions/common.sh
install_functions/checks.sh
install_functions/installCommon.sh
install_functions/wazuh-offline-installation.sh

related: https://github.com/wazuh/wazuh-packages/pull/3004
```console
root@ubuntu-jammy:~# bash wazuh-install.sh -a
30/09/2024 15:17:32 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
30/09/2024 15:17:32 INFO: Verbose logging redirected to /var/log/wazuh-install.log
30/09/2024 15:17:34 INFO: Verifying that your system meets the recommended minimum hardware requirements.
30/09/2024 15:17:34 INFO: Wazuh web interface port will be 443.
30/09/2024 15:17:38 INFO: Wazuh repository added.
30/09/2024 15:17:38 INFO: --- Configuration files ---
30/09/2024 15:17:38 INFO: Generating configuration files.
30/09/2024 15:17:39 INFO: Generating the root certificate.
30/09/2024 15:17:39 INFO: Generating Admin …
```

Change apt to dpkg for better performance.

---

cert_tool/certFunctions.sh
cert_tool/certMain.sh
install_functions/installCommon.sh
passwords_tool/passwordsFunctions.sh

close https://github.com/wazuh/wazuh-installation-assistant/issues/78
After comparing the files between the main branch of `wazuh-installation-assistant` and the master branch of `wazuh-packages`, I detected that some of the changes from the previous PRs had not been applied correctly. This PR fixes these errors.
```console
root@ubuntu-jammy:~# bash wazuh-install.sh -a
30/09/2024 19:02:53 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
30/09/2024 19:02:53 INFO: Verbose logging redirected to /var/log/wazuh-install.log
30/09/2024 19:02:53 INFO: Wazuh web interface port will be 443.
30/09/2024 19:02:57 INFO: Verifying that your system meets the recommended minimum hardware requirements.
30/09/2024 19:03:00 INFO: Wazuh repository added.
30/09/2024 19:03:00 INFO: --- …
```

Changes that remained pending after the migration of PRs to main

---

CHANGELOG.md
install_functions/checks.sh
install_functions/installMain.sh

Related: #65
The aim of this PR is to add a new logic to the installation assistant to check if the Wazuh central packages are available to install.
With this new development, we avoid that the installation is started when the packages are not available to install. 
The complete testing is: https://github.com/wazuh/wazuh-installation-assistant/issues/65#issuecomment-2379463820
A log example when the packages are not available to install:
```console
[root@ip-172-31-41-54 ec2-user]# bash wazuh-install.sh -a -v
27/09/2024 13:46:52 DEBUG: Checking root permissions.
27/09/2024 13:46:52 DEBUG: Checking sudo package.
27/09/2024 13:46:52 INFO: Starting Wazuh installation assistant. Wazuh version: 4.10.1
27/09/2024 13:46:52 INFO: Verbose logging redirected to /var/log/wazuh-install.log
27/09/2024 …
```

Added available packages check before installation

---

CHANGELOG.md
install_functions/checks.sh
install_functions/installMain.sh

Closes: https://github.com/wazuh/wazuh-installation-assistant/issues/83
The aim of this PR is to add more information about the supported architecture when performing an installation using the Wazuh installation assistant.
With this new development, it is clarified that the supported architecture is x86_64/AMD64.
```console
[root@ip-172-31-21-245 ec2-user]# bash wazuh-install.sh -a -v
02/10/2024 13:31:01 DEBUG: Checking root permissions.
02/10/2024 13:31:01 DEBUG: Checking sudo package.
02/10/2024 13:31:01 INFO: Starting Wazuh installation assistant. Wazuh version: 4.10.1 (x86_64/AMD64)
02/10/2024 13:31:01 INFO: Verbose logging redirected to /var/log/wazuh-install.log
02/10/2024 13:31:01 DEBUG: YUM package manager will be used.
02/10/2024 13:31:01 DEBUG: Checking system distribution. …
```

Added architecture information to assistant

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
.github/workflows/builder_installation_assistant.yml
.github/workflows/offline-installation.yml
CHANGELOG.md

Closes https://github.com/wazuh/wazuh-installation-assistant/issues/97
The aim of this PR is to add a new `WAZUH_INSTALLATION_ASSISTANT_REFERENCE` input to the `builder_installation_assistant`, `offline-installation`, `Test_installation_assistant_distributed` and `Test_installation_assistant` workflows.
- Running the `builder_installation_assistant` workflow:
- Running the `offline-installation` workflow:
- Running the `Test_installation_assistant_distributed` workflow:
- Running the `Test_installation_assistant` workflow:

Add input for wazuh installation assistant reference in workflows

---

.github/workflows/builder_installation_assistant.yml
CHANGELOG.md

The goal of this PR is to add the mandatory checksum field to the workflow for building the installation assistant packages.
With this, a new step has been added to generate the `sha512` files and another step to upload them to S3.
Additionally, an `echo` with the URI of each file uploaded to S3 has been added to better identify it.
>[!NOTE]
> This step implies that we have to upload the installation assistant files one by one to correctly obtain the URI of each file.
- https://github.com/wazuh/wazuh-installation-assistant/actions/runs/11295854932
- #105

Add checksum input and update the upload files to S3 steps

---

CHANGELOG.md
install_functions/indexer.sh

- https://github.com/wazuh/wazuh-installation-assistant/issues/122
The purpose of this PR is to contemplate the case in which the `filebeat_wazuh_template` cannot be downloaded because the link does not exist and then the execution of the script is stopped.
The `source_branch` variable that is defined in this execution is `v4.10.0` and this carries to a link that does not exist.
```shellsession
root@ip-172-31-32-65:/home/ubuntu/wazuh-installation-assistant# bash wazuh-install.sh -wi node-1 -d pre-release
28/10/2024 09:54:42 INFO: Starting Wazuh installation assistant. Wazuh version: 4.10.0
28/10/2024 09:54:42 INFO: Verbose logging redirected to /var/log/wazuh-install.log
28/10/2024 09:54:53 INFO: Verifying that your system meets the recommended minimum hardware requirements.
28/10/2024 …
```

Fixed bug when trying to download nonexistent filebeat_wazuh_template

---

CHANGELOG.md

related https://github.com/wazuh/wazuh-installation-assistant/issues/127
Merge 4.9.2 into 4.10.0

Merge 4.9.2 into 4.10.0

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
CHANGELOG.md

Previously, workflows that used Python failed with the new version of the runner that GitHub Actions utilizes. The most effective solution to resolve this issue is to use Python virtual environments (`venvs`). With `venvs`, we can create isolated environments that don’t interfere with the system's Python modules, making it the safest option.
For this, we had to modify two workflows that used Python in their execution:
- Test_installation_assistant
- Test_installation_assistant_distributed
In both workflows, the `venv` was added, and its correct execution was verified.
- Test_installation_assistant workflow: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/11669113874/job/32490341393
- Test_installation_assistant_distributed workflow: …

Add venv to installation assistant workflows

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
CHANGELOG.md

The purpose of this PR is to fix various bugs found in the installation assistant's test workflows.
Firstly, Ubuntu 22 has been added to the `Test_installation_assistant` matrix as a system, ensuring it functions correctly on pull requests, and the condition in the `Test_installation_assistant_distributed` matrix has also been fixed.
Additionally, the environment variable `WAZUH_INSTALLATION_ASSISTANT_REFERENCE` has been added so that if a pull request triggers the workflow, it uses the branch that activated it (`github.head_ref`) as a reference. If triggered manually, it will use the corresponding input (`WAZUH_INSTALLATION_ASSISTANT_REFERENCE`).
Lastly, some of the variables used in the workflow, like `VERBOSITY` and `AUTOMATION_REFERENCE`, were only set when the workflow was triggered …

Add matrix for pull request and fix provision playbook reference in test workflows

---

CHANGELOG.md
builder.sh

- https://github.com/wazuh/wazuh-installation-assistant/issues/24
The aim of this PR is to run the `getHelp` and show the usage options of the `builder.sh` script.
I peformed a test and run the `builder.sh` script with no parameters:
```shellsession
root@ubuntu-jammy:/home/vagrant/wazuh-installation-assistant# ./builder.sh 
NAME
builder.sh - Builds the Wazuh installation assistant and tools.
SYNOPSIS
builder.sh [-v] -i | -c | -p
DESCRIPTION
-i,  --installer
Builds the unattended installer single file wazuh-install.sh
-c,  --cert-tool
Builds the certificate creation tool wazuh-cert-tool.sh
-p,  --password-tool
Builds the password creation and modification tool wazuh-password-tool.sh
-h,  --help
Shows help.
```

Print `getHelp` output when no parameter is passed to the builder script

---

.gitignore
CHANGELOG.md
documentation-templates/wazuh/config.yml
documentation-templates/wazuh/filebeat/filebeat.yml

close https://github.com/wazuh/internal-devel-requests/issues/1785
For maintenance reasons, the filebeat.yml and config.yml files used in the Wazuh documentation are migrated to be published from the wazuh-installation-assistant repository.

Migrated documentation templates to wazuh-installation-assistant repository

---

CHANGELOG.md
install_functions/installCommon.sh
install_functions/installVariables.sh

This PR removes the conflict comment in installVariables.sh along with two variables that are not used during the Wazuh installation process.
- #148

Solve confict in installVariables

---

.gitignore
CHANGELOG.md
documentation-templates/wazuh/config.yml
documentation-templates/wazuh/filebeat/filebeat.yml
install_functions/filebeat.sh
install_functions/installMain.sh
install_functions/manager.sh

Related issue: https://github.com/wazuh/wazuh-installation-assistant/issues/156

Merge 4.10.0 into 4.10.1

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
.gitignore
CHANGELOG.md
documentation-templates/wazuh/config.yml
documentation-templates/wazuh/filebeat/filebeat.yml
install_functions/filebeat.sh
install_functions/installMain.sh
install_functions/manager.sh

Related issue: https://github.com/wazuh/wazuh-installation-assistant/issues/156

Merge 4.10.1 into 4.10.2

---

.github/actions/passwords-tool/tests-stack-failure.sh
.github/actions/passwords-tool/tests-stack-success.sh
.github/workflows/password-tool.yml
CHANGELOG.md

This PR aims to update the `-d` options in the password tool workflows as it used to be passed as an option to the builder script and now it has to be in the wazuh-install script to work properly.
Once this PR was opened, we found that the workflows were not working as expected, so we investigated and fixed the bugs in the files:
- `.github/actions/passwords-tool/tests-stack-success.sh`
- `.github/actions/passwords-tool/tests-stack-failure.sh` 
In addition, a workflow dispatch has been added in order to run it manually and make testing easier from now on.
- https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12396215542/job/34603731896?pr=170
- #162

Update `-d` option in the password tool workflow and fix test scripts

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
.github/workflows/builder_installation_assistant.yml
.github/workflows/offline-installation.yml
.github/workflows/password-tool.yml
CHANGELOG.md

- https://github.com/wazuh/wazuh-installation-assistant/issues/165
The aim of this PR is to change the Linux image used in the Github Actions runners that we use from `ubuntu-latest` to `ubuntu-22.04`.
- :white_check_mark: Test Installation Assistant [here](https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12412379480).
- :white_check_mark: Test Installation Assistant distributed [here](https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12413063840).
- :white_check_mark: Installation Assistant build [here](https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12396614774).
- :x: Offline Installation (this workflow is broken right now and we are working in the fix in [this issue](https://github.com/wazuh/wazuh-installation-assistant/issues/161). …

Change GHA runners to Ubuntu 22.04

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
.github/workflows/ansible-playbooks/aio.yml
.github/workflows/ansible-playbooks/distributed_install_dashboard.yml
.github/workflows/ansible-playbooks/distributed_install_indexer.yml
.github/workflows/ansible-playbooks/distributed_install_wazuh.yml
CHANGELOG.md
install_functions/installMain.sh
install_functions/installVariables.sh
tests/install/test_installation_assistant.py

Closes #47 
The objective of this PR is to improve the test completion status.
The solution was implemented where if the test of the Wazuh installation tools fails, the entire test is reported as failed. On the other hand, if only the test of the Wazuh components fails, the test is reported as successful (since the objective of the test is to validate the installation tools and not the functionality of Wazuh). Still, warnings are left in the component testing step, for later information to the responsible team.
- Stop execution of steps on failures:
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12518212911/job/34920285045
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/12518291928/job/34920498369
- Bug fixed in the installation wizard
- All test …

Improve asistant test completion status

---

CHANGELOG.md
install_functions/checks.sh
install_functions/installMain.sh
install_functions/installVariables.sh

Two functions have been created for validation of both the tag and the branch:
- **`checks_development_source_tag()`**: Validates that the current tag is correct by checking if it exists in the repository. If not, it uses the branch of the version being deployed for Wazuh.
- **`checks_source_branch()`**: Validates that the branch is correct by checking if it exists in the repository. If not, it uses `main`.
The `checks_development_source_tag()` function will modify the name of `source_branch` by appending the current stage. It is called when the `--development` flag is activated.
- The related tests can be found here: https://github.com/wazuh/wazuh-installation-assistant/issues/203#issuecomment-2598665310
- Correct branch 4.11.0 and incorrect stage
``` console
[root@xx-xx-xx-xx vagrant]# …
```

Add function to change the source_branch with the current stage with --develoment flag activated

---

CHANGELOG.md
install_functions/checks.sh
install_functions/installMain.sh

When trying to install Wazuh using the installation assistant, the following error is displayed:
```console
24/01/2025 21:17:38 ERROR: Error downloading wazuh-template.json file."
```
This error occurs because the template cannot be retrieved correctly, meaning the URL is incorrect. If we debug the code and print the URL it is trying to access (aiming to retrieve the URL for `v4.11.0-alpha1`), we get the following:
```console
Filebeat Wazuh template is: https://raw.githubusercontent.com/wazuh/wazuh/v4.11.0/extensions/elasticsearch/7.x/wazuh-template.json
```
The issue arises because `source_branch` is not being updated properly in the `filebeat_wazuh_template` variable.
Additionally, when trying to check the Filebeat URL in the `check_FilebeatURL()`  function, if the branch does not …

Fix error related with Filebeat template

---

install_functions/installVariables.sh

Due to #221, v4.11.0-alpha1 needs to be re-tagged, and therefore, the stage tag `alpha1` must be added in `installVariables.sh`.

Add alpha1 stage in installVariables before retag

---

install_functions/installVariables.sh

This PR aims to remove the alpha1 stage after retag `v4.11.0-alpha1`

Remove alpha1 stage in installVariables after retag

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
builder.sh
install_functions/checks.sh

This PR aims to update references to `master` in the `main` branch to align with modern naming conventions and inclusive practices.
> [!Note]
> There are additional occurrences of the word `master`, but they refer to the manager's master node.
- #231

Change master branch references to main

---

install_functions/installVariables.sh

related: https://github.com/wazuh/wazuh-installation-assistant/issues/255
Updated last_stage variable to 4.11.1 rc1

Updated last_stage variable to 4.11.1 rc1

---

CHANGELOG.md
install_functions/installCommon.sh

close https://github.com/wazuh/wazuh-installation-assistant/issues/258
The error occurred because in the control process, after removing the components, variables already set were reused. In the case of RPM, this generates a problem since the variable is set after the validation that the package is installed. When it is not installed, the variables are set to 1. This does not happen in APT because the variable is defined with the output of the control command.
The names of the variables are modified so that the uninstallation control has new variables and are set in case the package exists after uninstalling.
```console
[root@centos-7 ~]# bash /home/vagrant/wazuh-install.sh -u
28/02/2025 14:59:33 INFO: Starting Wazuh installation assistant. Wazuh version: 4.11.1 (x86_64/AMD64)
28/02/2025 …
```

Changed uninstall variables names

---

install_functions/installVariables.sh

Removed last_stage var from 4.11.1 rc1

Removed last_stage var from 4.11.1 rc1

---

CHANGELOG.md
install_functions/installCommon.sh

Related: https://github.com/wazuh/wazuh-virtual-machines/issues/225

Merge 4.11.1 into 4.12.0

---

CHANGELOG.md
install_functions/installVariables.sh

While https://github.com/wazuh/wazuh/issues/28566, the `wazuh_major` variable was left unencapsulated, preventing the installation assistant from being used.
This PR aims to fix this variable.

Fix `wazuh_major` version string

---

.github/workflows/Test_installation_assistant.yml
.github/workflows/Test_installation_assistant_distributed.yml
.github/workflows/builder_installation_assistant.yml
.github/workflows/offline-installation.yml
.github/workflows/password-tool.yml
CHANGELOG.md

The changes included in this PR aim to remove the default values of variables referencing the Wazuh-installation-assistant repository.
- https://github.com/wazuh/internal-devel-requests/issues/2137

Remove default installation assistant reference version from workflow

---

CHANGELOG.md
passwords_tool/passwordsFunctions.sh

close https://github.com/wazuh/wazuh-installation-assistant/issues/289
A change was detected in the `hash.sh` script provided by OpenSearch, affecting the output of the hashed message. This affects how we handled this output in our password tool.
The fix is ​​applied, and the following tests are performed:
Amazon Linux 2: https://github.com/wazuh/wazuh-installation-assistant/issues/289#issuecomment-2767027144
Ubuntu 22.04: https://github.com/wazuh/wazuh-installation-assistant/issues/289#issuecomment-2767009219

Fixed handling of hash.sh script output in Password Tool

---

CHANGELOG.md
install_functions/installVariables.sh
install_functions/wazuh-offline-download.sh
install_functions/wazuh-offline-installation.sh

close https://github.com/wazuh/wazuh-installation-assistant/issues/298
The Filebeat offline package download process had to be adapted following changes in the nomenclature of these packages.
- Amazon Linux 2023 x86_64 https://github.com/wazuh/wazuh-installation-assistant/issues/298#issuecomment-2789501771
- Amazon Linux 2023 aarch64 https://github.com/wazuh/wazuh-installation-assistant/issues/298#issuecomment-2787462069
- Ubuntu 22.04 amd64 https://github.com/wazuh/wazuh-installation-assistant/issues/298#issuecomment-2789660805
- Ubuntu 22.04 arm64 https://github.com/wazuh/wazuh-installation-assistant/issues/298#issuecomment-2789635832

Fixed offline download for Filebeat package

---

CHANGELOG.md

Related: https://github.com/wazuh/wazuh-installation-assistant/issues/364

delete 4.12.2 references from 4.13.0 branch

---

CHANGELOG.md

Related: https://github.com/wazuh/wazuh-installation-assistant/issues/364

delete 4.12.2 references from 4.14.0
