builder.sh
This PR is intended to include the changes from a PR that were added to `4.9.1` in the` wazuh-packages` repository.
- https://github.com/wazuh/wazuh-packages/issues/3099
- https://github.com/wazuh/wazuh-packages/pull/3110
=> Fix bug when changing the Filebeat URL in the Installation Assistant

builder.sh
This PR is intended to include the changes from a PR that were added to `4.9.1` in the `wazuh-packages` repository.
- https://github.com/wazuh/wazuh-packages/issues/3092
- https://github.com/wazuh/wazuh-packages/pull/3098
=> Change version to tag reference in source_branch references

CHANGELOG.md, SECURITY.md
Related: #58  
This PR includes Wazuh's security policy as requested in:
- https://github.com/wazuh/internal-devel-requests/issues/263
=> Update SECURITY.md file

passwords_tool/passwordsFunctions.sh
As part of #69, the aim of this PR is to bump https://github.com/wazuh/wazuh-packages/pull/3118 to this repository. The commits were cherry-picked.
=> Bumped "Change Filebeat passwords only when installing Wazuh Server or changing passwords "

install_functions/installMain.sh, install_functions/wazuh-offline-installation.sh
As part of #69, the aim of this PR is to bump https://github.com/wazuh/wazuh-packages/pull/3111 to this repository. The commits were cherry-picked.
=> Bumped "Offline Installation Assistant import the downloaded GPG Wazuh key." 

builder.sh, install_functions/installVariables.sh
=> Changed source_branch for 4.10.0-alpha1

builder.sh, install_functions/installVariables.sh
=> Change source branch

builder.sh, install_functions/installVariables.sh
This PR is related to https://github.com/wazuh/wazuh-installation-assistant/issues/102.
=> Revert source branch

.github/workflows/Test_installation_assistant.yml, .github/workflows/Test_installation_assistant_distributed.yml, CHANGELOG.md
related https://github.com/wazuh/wazuh-automation/issues/1891
Added a workaround to resolve the bug that occurs in Python, we will implement a better solution for 4.10.1
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/11352550040/job/31575551911
https://github.com/wazuh/wazuh-installation-assistant/actions/runs/11352555501/job/31575569948
=> Changed GitHub Runner version to fix Python error

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/116
=> change source branch to v4.10.0-alpha2

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/116
=> Revert source branch to v4.10.0

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/139
=> Changed source branch to alpha-3

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/139
=> Revert source branch for 4.10.0-alpha3

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/145
=> Revert source branch for 4.10.0-beta1

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/151
=> Change source branch to 4.10.0-rc1

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/151
=> Revert source branch for 4.10.0-rc1

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/167
=> Change source branch to 4.10.0-rc2

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/167
=> Revert source branch for 4.10.0-rc2

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/193
=> Changed source branch for 4.10.0-rc3

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/193
=> Revert source branch for 4.10.0-rc3

builder.sh, install_functions/installVariables.sh
=> Change source branch for v4.10.1-rc1

builder.sh, install_functions/installVariables.sh
=> Revert source branch for 4.10.1-rc1

install_functions/installVariables.sh
=> Change last_stage value

install_functions/installVariables.sh
=> Revert last_stage value

.github/workflows/builder_installation_assistant.yml, CHANGELOG.md
For every new support stage, we need to add the stage value to the last_stage variable, which makes the support process longer.
To solve this and avoid setting this variable manually for each support, the `builder_installation_assistant` has been modified to include a new option that automatically adds this variable to the `wazuh-install.sh` script, streamlining the process.
- Workflow execution: https://github.com/wazuh/wazuh-installation-assistant/actions/runs/13110249295
- Setted variable after execution:
```console
vagrant@ubuntu22-aio-4110-2547:~$ cat wazuh-install-3e2292a.sh | grep "last_stage="
last_stage="alpha1"
```
- AIO installation
```console
vagrant@ubuntu22-aio-4110-2547:~$ sudo bash wazuh-install-3e2292a.sh -a -d
03/02/2025 11:07:36 INFO: Starting Wazuh installation …
```
=> Add workflow step to add last_stage variable to the `wazuh-install.sh`

CHANGELOG.md
related https://github.com/wazuh/wazuh-installation-assistant/issues/227
=> Fixed changelog for 4.10.2

install_functions/installVariables.sh
related: https://github.com/wazuh/wazuh-installation-assistant/issues/235
=> Added last-stage variable with beta1

install_functions/installVariables.sh
close https://github.com/wazuh/wazuh-installation-assistant/issues/235
=> Removed last-stage variable

install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/241
=> Added last stage tag for v4.11.0-rc1

install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/241
=> Revert last stage for v4.11.0-rc1

install_functions/installVariables.sh
related https://github.com/wazuh/wazuh-installation-assistant/issues/255
Set last_stage var to empty
=> Set last_stage var to empty

install_functions/installVariables.sh
Updated last_stage variable to rc1
=> Updated last_stage variable to rc1

install_functions/installVariables.sh
=> Add last stage for 4.11.1-rc2

install_functions/installVariables.sh
=> Remove last stage from 4.11.1-rc2

.github/workflows/Test_installation_assistant.yml, .github/workflows/Test_installation_assistant_distributed.yml, .github/workflows/builder_installation_assistant.yml, .github/workflows/offline-installation.yml, .github/workflows/password-tool.yml, CHANGELOG.md, README.md, VERSION.json, builder.sh, install_functions/installVariables.sh, tests/unit/suites/test-common.sh, tests/unit/suites/test-dashboard.sh, tests/unit/suites/test-indexer.sh
close https://github.com/wazuh/wazuh-installation-assistant/issues/269
=> Bump branch 4.13.0 to 4.13.0 version

install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/281
=> Add tag to last stage variable for v4.11.2-rc1

install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/281
=> Revert last stage

install_functions/installVariables.sh
=> Add last stage for 4.11.2-rc2

install_functions/installVariables.sh
=> Remove last stage for 4.11.2-rc2

CHANGELOG.md
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/292
=> Merge 4.11.2 into 4.12.0

.github/workflows/Test_installation_assistant.yml, .github/workflows/Test_installation_assistant_distributed.yml, .github/workflows/offline-installation.yml, CHANGELOG.md, passwords_tool/passwordsFunctions.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/292
=> Merge 4.12.0 into 4.13.0

VERSION.json, install_functions/installVariables.sh
=> Add last stage for 4.12.0-alpha1

install_functions/installVariables.sh
=> Remove last stage for 4.12.0-alpha1

CHANGELOG.md, install_functions/installVariables.sh
close https://github.com/wazuh/wazuh-installation-assistant/issues/299
Added revision with a wildcard for the Filebeat package
<details>
<summary>Amazon Linux 2023 aarch64</summary>
```console
[ec2-user@ip-172-31-80-95 ~]$ cat /etc/*release
Amazon Linux release 2023.6.20241010 (Amazon Linux)
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.6.20241010"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/" …
```
=> Added revision to Filebeat package

.github/workflows/Test_installation_assistant.yml, .github/workflows/Test_installation_assistant_distributed.yml, .github/workflows/builder_installation_assistant.yml, .github/workflows/offline-installation.yml, .github/workflows/password-tool.yml, CHANGELOG.md, VERSION.json, builder.sh, install_functions/installVariables.sh, tests/unit/suites/test-common.sh, tests/unit/suites/test-dashboard.sh, tests/unit/suites/test-indexer.sh
close https://github.com/wazuh/wazuh-installation-assistant/issues/302
Bump 4.12.1 branch
=> Bump 4.12.1 branch

CHANGELOG.md, install_functions/installVariables.sh, install_functions/wazuh-offline-download.sh, install_functions/wazuh-offline-installation.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/306
=> Merge 4.12.0 into 4.12.1

.github/workflows/Test_installation_assistant.yml, .github/workflows/Test_installation_assistant_distributed.yml, .github/workflows/builder_installation_assistant.yml, .github/workflows/offline-installation.yml, .github/workflows/password-tool.yml, CHANGELOG.md, install_functions/installVariables.sh, install_functions/wazuh-offline-download.sh, install_functions/wazuh-offline-installation.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/306
=> Merge 4.12.1 into 4.13.0

VERSION.json, install_functions/installVariables.sh
Related issue: https://github.com/wazuh/wazuh-installation-assistant/issues/316
=> Bump 4.12.0-rc1

install_functions/installVariables.sh
Related issue: https://github.com/wazuh/wazuh-installation-assistant/issues/316
=> Revert last stage for 4.12.0-rc1

.github/workflows/Test_installation_assistant.yml, .github/workflows/Test_installation_assistant_distributed.yml, .github/workflows/builder_installation_assistant.yml, .github/workflows/offline-installation.yml, .github/workflows/password-tool.yml, CHANGELOG.md, VERSION.json, builder.sh, install_functions/installVariables.sh, tests/unit/suites/test-common.sh, tests/unit/suites/test-dashboard.sh, tests/unit/suites/test-indexer.sh
=> Bump to 4.12.2

CHANGELOG.md, install_functions/checks.sh
Closes #326
The objective of this PR is to include OS AL2023 in the list of recommended operating systems.
Clone and checkout the branch:
```
root@stack-debian12:/home/vagrant# git clone https://github.com/wazuh/wazuh-installation-assistant.git
Cloning into 'wazuh-installation-assistant'...
remote: Enumerating objects: 2707, done.
remote: Counting objects: 100% (511/511), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 2707 (delta 473), reused 392 (delta 387), pack-reused 2196 (from 2)
Receiving objects: 100% (2707/2707), 875.11 KiB | 4.68 MiB/s, done.
Resolving deltas: 100% (1580/1580), done.
root@stack-debian12:/home/vagrant# cd wazuh-installation-assistant/
root@stack-debian12:/home/vagrant/wazuh-installation-assistant# git checkout …
```
=> Include AL2023 in the recommended OSs list 

.github/actions/offline-installation/common.sh, .github/workflows/Test_installation_assistant_tier.yml, .github/workflows/builder_installation_assistant.yml, CHANGELOG.md, README.md, VERSION.json, builder.sh, install_functions/installCommon.sh, install_functions/installVariables.sh, tests/install/test_installation_assistant.py, tests/unit/suites/test-common.sh, tests/unit/suites/test-dashboard.sh, tests/unit/suites/test-filebeat.sh, tests/unit/suites/test-indexer.sh, tests/unit/suites/test-installCommon.sh
close https://github.com/wazuh/wazuh-installation-assistant/issues/332
Bumped 6.0.0 branch to 6.0.0 version
=> Bumped 6.0.0 branch

.github/workflows/Test_installation_assistant.yml, .github/workflows/Test_installation_assistant_distributed.yml, .github/workflows/builder_installation_assistant.yml, .github/workflows/offline-installation.yml, .github/workflows/password-tool.yml, CHANGELOG.md, VERSION.json, builder.sh, install_functions/installCommon.sh, install_functions/installVariables.sh, tests/install/test_installation_assistant.py, tests/unit/suites/test-common.sh, tests/unit/suites/test-dashboard.sh, tests/unit/suites/test-filebeat.sh, tests/unit/suites/test-indexer.sh, tests/unit/suites/test-installCommon.sh
=> Bump 5.0.0 version

builder.sh, install_functions/installVariables.sh
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/347
=> Revert source branch for 4.10.2-rc1

.github/workflows/Test_installation_assistant.yml, .github/workflows/Test_installation_assistant_distributed.yml, .github/workflows/builder_installation_assistant.yml, .github/workflows/offline-installation.yml, .github/workflows/password-tool.yml, CHANGELOG.md, README.md, VERSION.json, builder.sh, install_functions/installVariables.sh, tests/unit/suites/test-common.sh, tests/unit/suites/test-dashboard.sh, tests/unit/suites/test-indexer.sh
=> Bump to 4.14.0 version

VERSION.json, install_functions/installVariables.sh
=> Bump to 4.12.1-rc1

CHANGELOG.md
- https://github.com/wazuh/wazuh-installation-assistant/issues/376
=> Merge 4.14.0 into main

VERSION.json
Issue: https://github.com/wazuh/wazuh-installation-assistant/issues/372
=> Bump test/372-integrate-bumper-script-via-github-action branch

.github/workflows/4_bumper_repository.yml
This PR updates the environment secret used during repository checkout
- https://github.com/wazuh/wazuh-installation-assistant/issues/372
- https://github.com/wazuh/wazuh-qa-automation/issues/2126
=> Fix repository bumper workflow github references

VERSION.json
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/385
=> Bump stage to alpha1 for 4.13.0 branch

.github/workflows/4_bumper_repository.yml, VERSION.json
This PR is related to https://github.com/wazuh/wazuh-installation-assistant/issues/395
=> Bumpe from 4.13.0 to 4.13.1

CHANGELOG.md, install_functions/wazuh-offline-download.sh
Related to https://github.com/wazuh/wazuh-installation-assistant/issues/387
The goal of this PR is to increase the revision of the Filebeat package according to these changes https://github.com/wazuh/wazuh/issues/29397
They will be executed when we have packages
=> Increase filebeat revision

.github/workflows/builder_installation_assistant.yml, VERSION.json
Issue: https://github.com/wazuh/wazuh-qa-automation/issues/2625
=> Bump test/554-test branch

.github/workflows/builder_installation_assistant.yml, VERSION.json
Issue: https://github.com/wazuh/wazuh-qa-automation/issues/2654
=> Bump 4.13.0 branch

builder.sh, install_functions/installVariables.sh
=> Revert source branch for 4.10.3-rc1

CHANGELOG.md
Related: https://github.com/wazuh/wazuh-installation-assistant/issues/436
=> Merge 4.13.0 into 4.14.0

.github/workflows/builder_installation_assistant.yml, CHANGELOG.md, config/dashboard/dashboard.yml, config/dashboard/dashboard_all_in_one.yml, config/dashboard/dashboard_assistant.yml, config/dashboard/dashboard_assistant_distributed.yml
=> Merge 4.14.1 into main
